# Generated by Django 3.2.12 on 2024-06-11 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apialumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('tut_id', models.AutoField(primary_key=True, serialize=False)),
                ('tut_ci', models.CharField(max_length=8)),
                ('tut_ruc', models.CharField(max_length=10)),
                ('tut_tipo', models.CharField(choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Tutor legal', 'Tutor legal'), ('Otro', 'Otro')], max_length=20)),
                ('tut_nom', models.CharField(max_length=100)),
                ('tut_ape', models.CharField(max_length=100)),
                ('tut_tel', models.CharField(max_length=20)),
                ('tut_direc', models.CharField(max_length=200)),
                ('tut_mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TutorAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apialumnos.alumno')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitutores.tutor')),
            ],
        ),
    ]
