# Generated by Django 3.2.12 on 2024-06-13 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitutores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='tut_ruc',
        ),
    ]
