# Generated by Django 3.2.12 on 2024-06-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('alum_id', models.AutoField(primary_key=True, serialize=False)),
                ('alum_ci', models.CharField(max_length=8)),
                ('alum_nom', models.CharField(max_length=100)),
                ('alum_ape', models.CharField(max_length=100)),
                ('alum_fecha_nac', models.DateField()),
                ('alum_edad', models.PositiveIntegerField(editable=False)),
            ],
        ),
    ]
